# Generated by Django 3.0.2 on 2020-01-21 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=70)),
                ('tag1', models.CharField(blank=True, max_length=15)),
                ('tag2', models.CharField(blank=True, max_length=15)),
                ('tag3', models.CharField(blank=True, max_length=15)),
                ('shortDescription', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('github_link', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('project_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.Author')),
            ],
        ),
    ]
