# Generated by Django 3.0.2 on 2020-01-13 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(blank=True, max_length=100)),
                ('service_languages', models.CharField(blank=True, max_length=100)),
                ('service_description', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.Author')),
            ],
        ),
    ]
