# Generated by Django 3.0.2 on 2020-01-13 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('my_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('resume', models.ImageField(blank=True, null=True, upload_to='photos/File/%Y/%m/%d/')),
                ('summary', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('high_school', models.CharField(blank=True, max_length=30)),
                ('high_school_title', models.CharField(blank=True, max_length=150)),
                ('high_school_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('high_school_graduated', models.CharField(blank=True, max_length=50)),
                ('community_college', models.CharField(blank=True, max_length=30)),
                ('community_college_title', models.CharField(blank=True, max_length=150)),
                ('community_college_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('community_college_graduated', models.CharField(blank=True, max_length=50)),
                ('university', models.CharField(blank=True, max_length=30)),
                ('university_title', models.CharField(blank=True, max_length=150)),
                ('university_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('university_graduated', models.CharField(blank=True, max_length=50)),
                ('university_honors_list', models.CharField(blank=True, max_length=150)),
                ('university_honors_list_link', models.CharField(blank=True, max_length=150)),
                ('experience_1_company', models.CharField(blank=True, max_length=50)),
                ('experience_1_position', models.CharField(blank=True, max_length=50)),
                ('experience_1_description', models.TextField(blank=True)),
                ('experience_1_hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('experience_2_company', models.CharField(blank=True, max_length=50)),
                ('experience_2_position', models.CharField(blank=True, max_length=50)),
                ('experience_2_description', models.TextField(blank=True)),
                ('experience_2_hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('experience_3_company', models.CharField(blank=True, max_length=50)),
                ('experience_3_position', models.CharField(blank=True, max_length=50)),
                ('experience_3_description', models.TextField(blank=True)),
                ('experience_3_hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
