# Generated by Django 3.0.2 on 2020-01-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_company', models.CharField(blank=True, max_length=50)),
                ('experience_position', models.CharField(blank=True, max_length=50)),
                ('experience_desc_point1', models.CharField(blank=True, max_length=100)),
                ('experience_desc_point2', models.CharField(blank=True, max_length=100)),
                ('experience_desc_point3', models.CharField(blank=True, max_length=100)),
                ('experience_desc_point4', models.CharField(blank=True, max_length=100)),
                ('experience_desc_point5', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('experience_hire_date', models.DateTimeField(blank=True)),
                ('experience_end_date', models.DateTimeField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.Author')),
            ],
        ),
    ]
